name: Update git ref in Dockerfiles

on:
  workflow_dispatch:
    inputs:
      swow_ref:
        description: 'Swow git ref to build'
        required: true
        default: 'develop'

jobs:
  update:
    name: Update git ref in Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Prepare git repo
        run: |
          git clone --single-branch --depth 1 -b master https://github.com/${{ github.repository }} docker-swow
          cd docker-swow
          git checkout -b build

      - name: Replace "develop" in Dockerfiles
        working-directory: docker-swow
        run: |
          git checkout master .
          sed -i 's|develop|${{ github.event.inputs.swow_ref }}|g' dockerfiles/*/*/Dockerfile

      - name: Re-commit changes
        working-directory: docker-swow
        run: |
          git add -A
          # todo: maybe we should use real email and name?
          git config --global user.email "none@none.net"
          git config --global user.name "actions-bot"
          git commit -m "Update Swow to libcat/libcat@${{ github.event.inputs.swow_ref }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build