name: Update git ref in Dockerfiles

on:
  workflow_dispatch:
    inputs:
      swow_ref:
        description: 'Swow git ref used in alias'
        required: true
        default: 'develop'
      swow_rev:
        description: 'Swow git hash to build'
        required: true

jobs:
  update:
    name: Update git ref in Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Replace "develop" in Dockerfiles
        run: |
          git checkout -b build
          git pull --ff-only
          git checkout master .
          sed -i 's|develop|${{ github.event.inputs.swow_rev }}|g' dockerfiles/*/*/Dockerfile

      - name: Re-commit changes
        run: |
          git add -A
          # todo: maybe we should use real email and name?
          git config --global user.email "none@none.net"
          git config --global user.name "actions-bot"
          git commit -m "Update Swow to libcat/libcat@${{ github.event.inputs.swow_rev }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:

          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build